### ISSUE TITLE
aom.idl not updated (deleted) when IDL was removed from spec

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy-reports#10]
In https://github.com/web-platform-tests/wpt/pull/9759#issuecomment-405445178 @alice pointed out that https://wicg.github.io/aom/spec/ no longer has any IDL. This happened in https://github.com/WICG/aom/commit/4a21b8512146db611e8b8fa24d2b88b185b7095b#diff-f2d8594ce0e9581fcd475b98f2fe2a82, over a month ago.

The aom.idl files should be deleted, and it would be good with some process to do this automatically, or flag that human attention is required.

**Comment by tidoust** [comment]
Right. I had noticed the switch from one spec to multiple sub-specs some time ago, but had not realized that the IDL content had changed as a result. I was planning to address this case one way or the other, just didn't manage to find the time.

The addition/removal of IDL files to and from the repo is manual and that's something we somewhat wanted to keep this way for now, see #12. Presented differently, we don't yet have good failure detection mechanisms in place in Reffy, so if we automate addition/removal, there's a good chance that once every few days, a random IDL file will get deleted from the report because of some transient network or other error (e.g. a ReSpec update that makes ReSpec generation crash in Reffy) that prevented the generation of the IDL file. The IDL file would be added back the day after, but it seems better to keep the known version.

I dropped the `aom.idl` file from the report. I'll drop the spec from Reffy's crawl as well: 
1. parsing the main index spec does not make any sense
2. The IDL content in the aria-reflection spec is actually an informative copy of the content defined in WAI-ARIA 1.2, and Reffy will be confused, thinking the IDL content is normative.

I'll add WAI-ARIA 1.2 to the list of specs to crawl instead, which should eventually generate a `wai-aria.idl` file.

**Comment by foolip** [comment]
Thanks for the explanation and manual fix, @tidoust!

> Presented differently, we don't yet have good failure detection mechanisms in place in Reffy, so if we automate addition/removal, there's a good chance that once every few days, a random IDL file will get deleted from the report because of some transient network or other error (e.g. a ReSpec update that makes ReSpec generation crash in Reffy) that prevented the generation of the IDL file. The IDL file would be added back the day after, but it seems better to keep the known version.

This is reminiscent of issues with ReSpec that @mdittmer had with https://github.com/mdittmer/web-apis. After http://lists.w3.org/Archives/Public/public-script-coord/2015JulSep/0074.html and a bunch of efforts by ReSpec maintainers, I think there are now no uses of the old style IDL left, and it's possible to extract IDL from the raw response without using PhantomJS or simliar. (I don't know what reffy-reports does.)

**Comment by tidoust** [comment]
> it's possible to extract IDL from the raw response without using PhantomJS or simliar. (I don't know what reffy-reports does.)

IDL is just one of the things that Reffy extracts from specs. It also extracts the list of normative and informative references, which ReSpec generates on-the-fly, and long-term goal would also be to extract term definitions and basically anything that could perhaps be interesting info to analyse from a cross-spec perspective. Generation is also useful in the couple of cases where raw specs use ReSpec's Markdown mode. We also wanted to stay close to analyzing what readers see, in case the generation would create artefacts.

Anyway, we don't need to run all ReSpec modules and could restrict ReSpec generation to the ones we need instead of running a full generation. As a matter of fact, we had to hack a number of things to make ReSpec run under JSDOM, disabling a couple of modules that cannot run as-is among other things, and the [resulting code](https://github.com/tidoust/reffy/blob/master/src/lib/jsdom-monkeypatch.js) is ugly, so there's definitely room for improvement.
