### ISSUE TITLE
webstorage spec is missing

### ISSUE THREAD

**Issue by lukebjerring** [tidoust/reffy-reports#14]
Spec: https://www.w3.org/TR/webstorage/
Tests: https://wpt.fyi/webstorage

**Comment by lukebjerring** [comment]
@tidoust if there's a trivial flow for me to self-resolve these as I file them, let me know :)

**Comment by lukebjerring** [comment]
Uh, disregard this issue. The content of `webstorage` is all in `html` (which, personally, I don't agree with, but hey.)

**Comment by tidoust** [comment]
Hmm, are you sure you want to add that one? That spec has been folded into the HTML LS spec, and thus the IDL it defines already appears in `html.idl` (and will be tested as part of that).

Reffy crawls that spec to create the W3C-centric perspective, given that HTML 5.3 does not include Web Storage. Not including that spec in the WHATWG-centric crawl was done on purpose.

Process-wise, I won't claim it is trivial, but I'm happy to give you push rights on both `reffy` and `reffy-reports`. To add an IDL spec, the easiest way would probably be:

1. In Reffy, add the spec URL to [`specs-idl.json`](https://github.com/tidoust/reffy/blob/master/src/specs/specs-idl.json)
2. Then run the generation locally [following the instructions](https://github.com/tidoust/reffy#installation), running `npm run all` (note you'll need a W3C API key set in a `config.json` file). This should generate reports, including IDL dumps in a `reports` folder.
3. Copy over the generated IDL file to the right position (two copies, one in the `w3c` folder and one in the `whatwg` folder) in a clone of the `reffy-reports` repository
4. Git add, commit and push the IDL files

Steps 2, 3, 4 are needed because the code that runs Reffy daily on a server does not add new IDL files to `reffy-reports` automatically. Alternatively, you could simply create placeholders (empty files) in `reffy-reports`, and the files should get filled with the right IDL content on the next day.

**Comment by tidoust** [comment]
Ah, I see our comments just collided :)
