### ISSUE TITLE
Space in "readonly maplike<DOMString, object>" removed from WebRTC

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy-reports#15]
https://w3c.github.io/webrtc-pc/#rtcstatsreport-object has this IDL:
```
[Exposed=Window]
interface RTCStatsReport {
    readonly maplike<DOMString, object>;
};
```

The source also has a space after "readonly":
https://github.com/w3c/webrtc-pc/blob/f3850347f2f0bcadbad716664cd1543eddd172ca/webrtc.html#L10086

But in reffy-reports, there's a space missing:
https://github.com/tidoust/reffy-reports/blob/497e8f76f4d342b2400c131670788fe04596e1fb/whatwg/idl/webrtc.idl#L591

Possibly this is a bug in some whitespace normalization?

**Comment by foolip** [comment]
@lukebjerring discovered this in https://github.com/web-platform-tests/wpt/pull/11700.

**Comment by tidoust** [comment]
Interesting. That's actually a bug in recent versions of ReSpec, see w3c/respec#1794. This bug does not affect the Editor's Draft of the WebRTC spec yet because that spec references an old version of ReSpec. It does affect Reffy because Reffy forces the latest version of ReSpec when it crawls specs.

Note the bug also affects [some definitions of the Web MIDI API spec](https://github.com/w3c/respec/issues/1794).

**Comment by marcoscaceres** [comment]
Fix incoming... will release later today.

**Comment by foolip** [comment]
https://github.com/w3c/respec/issues/1794 was fixed and the spaces came back in reffy-reports in 1a526db6edea4a9639200da4c3d68ded729c2f29. Thanks @tidoust and @marcoscaceres!

**Comment by marcoscaceres** [comment]
Glad it worked - apologies for breaking it.

**Comment by foolip** [comment]
I don't know what caused it and thus what would have prevented it, but https://github.com/foolip/bikeshed-tests is a think I did for Bikeshed to have all the known specs as tests for any code changes, maybe that would be useful for ReSpec too?

**Comment by marcoscaceres** [comment]
Could definitely be useful. I need to see how they work, but I guess having expected inputs and outputs would be nice.
