### ISSUE TITLE
Trigger wpt interfaces/ updates in master Travis job in this repo

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy-reports#20]
Bonjour,

In https://github.com/foolip/wpt-idl-importer I've written half of a solution for https://github.com/web-platform-tests/wpt/issues/7784, creating branches but not opening PRs.

That's triggered on a daily Travis cron job that runs slightly after when I've observed the updates in this repo to happen. However, it's still an extra delay and if updates to this repo start happening faster, wpt updates won't get any faster.

So, I think it would be a good idea to let a Travis job in this repo trigger the updates. I'd be happy to maintain it of course, and would probably write it in node to match Reffy itself.

Thoughts?

**Comment by tidoust** [comment]
Yes, that makes sense!

No problem to add a Travis job that reacts on push. I added you as collaborator to the project (and to Reffy), although I suspect that's not going to be enough to create the right Travis job. Happy to do that once ready.

It's great if you can stick to node.js, but then other languages are ok too (I'm not sure I get the dependency on Python in `wpt-idl-importer` by the way, the shell script does not seem to be calling any Python code?)

Actually, we should run the daily update as a Travis cron task too, be it only to get notified when something goes wrong. Which should be relatively easy (we just need to update Reffy's code to look at environment variables for the W3C API Key instead of in a `config.json` file). But that's a separate issue.

**Comment by foolip** [comment]
Thanks @tidoust!

Would you mind visiting https://travis-ci.org/tidoust/reffy and https://travis-ci.org/tidoust/reffy-reports and enabling Travis for the repos there? After that, I think I should be able to experiment with the rest by just pushing .travis.yml to branches.

> It's great if you can stick to node.js, but then other languages are ok too (I'm not sure I get the dependency on Python in wpt-idl-importer by the way, the shell script does not seem to be calling any Python code?)

I'll stick to node.js. I had planned to write something in Python in wpt-idl-importer, but didn't. I'll rewrite the shell scripts to use JS as far as possible.

> Actually, we should run the daily update as a Travis cron task too, be it only to get notified when something goes wrong.

That would be nice, yeah. It would, however, limit updates to being daily, and I also think it would be nice if they happened even faster :)

**Comment by tidoust** [comment]
> Would you mind visiting https://travis-ci.org/tidoust/reffy and https://travis-ci.org/tidoust/reffy-reports and enabling Travis for the repos there? After that, I think I should be able to experiment with the rest by just pushing .travis.yml to branches.

Done!

**Comment by foolip** [comment]
Thank you! That was enough for me to trigger https://travis-ci.org/tidoust/reffy-reports/builds/417189458, so now I can iterate.

To make it eventually really create PRs on web-platform-tests, I'll need a GH_TOKEN environment variable in the Travis config. Will email you.
