### ISSUE TITLE
Too many valueParseError since Marc 16 2019 in w3c/crawl.json

### ISSUE THREAD

**Issue by abhishiv** [tidoust/reffy-reports#31]
Hey guys 

Many thanks for publishing this!

Just notice that there are too many valueParseError since Marc 16 2019. They seem to be because of some encoding issue upstream.

Here's an example
```
          "<final-bg-layer>": {
            "value": "<‘background-color’> || <bg-image> || <bg-position> [ / <bg-size> ]? || <repeat-style> || <attachment> || <box> || <box>",
            "valueParseError": "Unrecognized token <‘background-color’>"
          },
```

https://github.com/tidoust/reffy-reports/blob/19a80a9de50cb62ad33f3987c63198d34bf17c15/w3c/crawl.json

**Comment by tidoust** [comment]
Hi @abhishiv,

I do not know what changes may have happened on March 16 2019, but these errors are, I believe, due to the fact that Reffy does not expect curly quotes in the definitions because the grammar does not seem to allow for them, see point 4. in https://github.com/w3c/csswg-drafts/issues/2921

Given that more and more specs seem to be using curly quotes, the CSS grammar parser should be updated in Reffy to support them.

**Comment by tidoust** [comment]
Hack implemented and proper support for curly quotes now tracked in https://github.com/tidoust/reffy/issues/148

The errors should disappear next time the crawler runs (in about a day or so). Closing this issue accordingly.
