### ISSUE TITLE
WebIDL snippets with default values are being dropped

### ISSUE THREAD

**Issue by lukebjerring** [tidoust/reffy-reports#34]
e.g. https://github.com/w3c/wake-lock/commit/5c34f9a299ad4625fe32398152bf85ab8cdf1c24 lead to https://github.com/web-platform-tests/wpt/pull/17904/files#diff-d83394caf586049a88f0c0cdd880c7bbL12

e.g. https://github.com/w3c/push-api/commit/9179964494a5cedcca4a104c555e98019fbb1135 lead to https://github.com/web-platform-tests/wpt/pull/17826/files#diff-173f90f4b0be112b694720eda63bce08L11

**Comment by foolip** [comment]
Oh, good catch. That suggests that some attempt is being made to parse the IDL before accepting it, but that doesn't jive with my experience of fixing lots of broken IDL in specs that was already in reffy-reports... curious to learn what's behind this :)

**Comment by foolip** [comment]
@tidoust @dontcallmedom can either of you help out with this?

**Comment by tidoust** [comment]
Argh. The problem is that right now, Reffy needs to use a pinned version of Respec (23.7.1) because newer versions of Respec do not run under JSDOM (notably because of the use of `CreateObjectURL` to create a worker). That old version of Respec does not seem to like default values when it parses WebIDL fragments and fails to include the interface in the final IDL index.

I don't know how to make the latest version of Respec run with JSDOM. We may have to get back to running a headless browser instead.

In the meantime, I'll have Reffy extract the IDL from the body of the spec instead of relying on the IDL index at the end of the spec.

**Comment by tidoust** [comment]
Reffy will now ignore the final IDL index from now on, and rather extract IDL definitions from the core part of the spec.

Not to have to wait for tomorrow's automatic report, I also pushed a manual update of the IDL files for Performance Timeline, Push API, User Timing, Wake Lock, WebNFC and Web Share, which had missing IDL definitions because of this.

Please reopen the issue if I missed something!

**Comment by foolip** [comment]
Sweet, thanks for fixing this, @tidoust!
