### ISSUE TITLE
Error in crawl.json reading property version-history of undefined

### ISSUE THREAD

**Issue by domenic** [tidoust/reffy-reports#36]
As of the time of this writing, many entries in https://tidoust.github.io/reffy-reports/whatwg/crawl.json contain no IDL. Instead they contain an error field:

```
TypeError: Cannot read property 'version-history' of undefined TypeError: Cannot read property 'version-history' of undefined\n    at fetch.then.then.s (/home/dom/github.com/reffy/src/lib/util.js:316:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Examples are entries 231 (worklets-1), 227 (webrc-stats), 225 (webmidi), and more.

**Comment by tidoust** [comment]
Sorry for the late response here.

This happens when the W3C API is down when the crawl runs. That used to happen a lot before but the underlying bug had been fixed. I don't know why the problem has started to re-appear from time to time recently.

From Reffy's perspective, I have a long standing issue to detect and report the problem properly: https://github.com/tidoust/reffy/issues/75

I hadn't worked on it because

**Comment by tidoust** [comment]
Closing this issue as, following switch to using [w3c/browser-specs](https://github.com/w3c/browser-specs/) as the source list of specs to crawl, Reffy no longer depends on the W3C API, so this error won't happen again.
