### ISSUE TITLE
Trim any trailing whitespace

### ISSUE THREAD

**Issue by lukebjerring** [tidoust/reffy-reports#5]
Some files, due to an inconsistent whitespace offset, end up with trailing whitespace.
e.g. https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/geolocation-API.idl

Note: when I was doing these scrapes, I treated each individual snippet independently when trimming any common leading whitespace, which had a nicer result for inconsistent snippets - not sure if that's trivial in your pipeline or not.

**Comment by lukebjerring** [comment]
Another example:
https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/orientation-event.idl

**Comment by tidoust** [comment]
That depends on what you call "individual snippet". The two specs you mention do not have an IDL index, so Reffy extracts snippets as it finds them in the spec. But then the DeviceOrientation spec merely contains two large snippets, so trimming trailing whitespaces for each snippet won't improve the situation a lot.

Any pointer to what you were doing on IDL snippets? And what do you want to achieve? Complete reindent? Or just remove leading whitespaces before `interface` and other definitions?

**Comment by lukebjerring** [comment]
Yeah, makes sense. No worries - This issue is just hoping to have the output of reffy-reports pass the lint check in web-platform-tests/wpt, which doesn't allow _trailing_ whitespace (which only seems to be the case on otherwise-empty lines).

**Comment by tidoust** [comment]
Sorry, I was confused because, while the issue title uses the term _trailing_, your comment also mentioned _leading_ whitespaces. Removing trailing whitespaces is easy, I'll do it.

Removing leading whitespaces in a way that makes sense (that is, re-indenting the IDL properly) is more challenging. The code has access to the IDL tree and could re-serialize it in theory, but I feel wary of doing any "complex" treatment on the extracted IDL, not to introduce side-effects, especially given the fact that specs contain invalid IDL constructs from time to time.

**Comment by lukebjerring** [comment]
Looks good! Thanks.
